### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Nucleuss** [madskristensen/WebExtensionPack#14]
Hey madskristensen, your VS extension seems pretty cool, and i would like your help getting it installed! thanks in advance!

**### Installed product versions**

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3

**Extension**

Web Extension Pack 2015 - 1.8.54

### Description

Fails to install correctly. When i launch VS it prompts me with a message informing me that that the extension is installing, it than asks me to restart to finish the installation. If i restart VS and relaunch it behaves like  the extension is not installed and needs to be, so it starts installing it again, and asks me to restart like before.. than a little while later ( after giving up and taking a break) i realized it was outputting some info in my Output window. 

```
11/29/2016 2:51:22 PM: Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
- Web Developer Tools
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp, Boolean enforceCertificateCheckForUpgrade)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.Install(IInstallableExtension extension, Boolean perMachine)
   at WebExtensionPack.VSPackage.InstallExtension(IVsExtensionRepository repository, IVsExtensionManager manager, KeyValuePair`2 product, DataStore store) in C:\projects\webextensionpack\src\VSPackage.cs:line 100
```

### Steps to recreate

N/A

### Current behavior

Failing to install.

**Comment by Nucleuss** [comment]
I am pretty silly, and this is a easy to fix problem.

-Use add and remove programs to change your Visual Studio installation.
-Tick the Web Development Tools 
-????
-Profit!
